/* ============================================================================
   I PROMPT DEGLI ASSET DERIVATI — TEMPLATE TECNICI, NON DESIGN

   🔷 «Il Character Master è la decisione visiva. Gli asset derivati la
      conservano e la mettono in scena.»

   ════════════════════════════════════════════════════════════════════════════
   COM'ERA, E PERCHÉ ERA SBAGLIATO

   Dopo il master, ogni altro asset riceveva di nuovo TUTTO: Family, Archetipo,
   Affinità, Taglia, Ruolo, Fashion, umore, Character DNA, Cultural DNA,
   Character Design DNA, capelli, occhiali, palette, rarità, regole di casa.
   Sedicimila caratteri, gli stessi del master, più una riga in cima che
   diceva «comunque vince l'immagine allegata».

   Due danni, e il secondo è peggiore del primo.

   1. SI PAGAVA DUE VOLTE LA STESSA COSA. Il ragionamento creativo era già
      stato fatto — dal Resolver, con il modello grande — e finiva nel master.
      Rimandarlo per intero altre cinque volte non aggiungeva una decisione.

   2. SI INVITAVA A RIDECIDERE. Un modello che riceve un briefing completo di
      character design fa character design: è quello che il testo gli chiede.
      Poi la riga sul riferimento gli dice di non farlo. Gli davamo un ordine e
      il suo contrario, e il risultato dipendeva da quale dei due pesava di più
      quel giorno — che è esattamente il motivo per cui le sei immagini non si
      somigliavano.

   🔒 ADESSO L'INFORMAZIONE STA NELL'IMMAGINE, NON NEL TESTO. Il master viene
   allegato davvero (`generate.ts` → `assetBase64`), e il testo che lo
   accompagna dice solo la trasformazione di produzione da fare. Poche righe,
   nessuna tassonomia, nessuna interpretazione culturale, nessun designer.

   ⚠️ QUELLO CHE QUESTI TEMPLATE NON DEVONO MAI CONTENERE: Family, Archetipo,
   Affinità, Ruolo, Fashion, umore, Character DNA, Cultural DNA, il designer,
   la rarità, l'anatomia, i capelli, gli occhiali, la palette. Non perché siano
   sbagliati — perché sono GIÀ DECISI, e ripeterli è un invito a rifarli.
   `verify:package` lo verifica cercando quelle parole qui dentro.
   ════════════════════════════════════════════════════════════════════════════

   🔒 DETERMINISTICI. Nessuna chiamata a un modello di testo: sono `const` con
   dentro solo la grammatica dell'asset. Chiamare un'AI per riscrivere una
   frase che il programma conosce già è la definizione di spesa senza valore.

   🔒 E SOLO PER LE CREATURE NUOVE. Un .mon nato prima ha i suoi prompt
   compilati e §29 dice che una creatura tiene la versione con cui è nata:
   `promptFor` decide quale strada, e questa vale quando c'è una risoluzione e
   il master esiste davvero.
   ========================================================================= */

import type { AssetType } from '../engine/types';
import { EXPRESSION_SPEC, assetTypeDef } from '../engine/assets';

/**
 * La testata comune: identità bloccata, e cosa non si tocca.
 *
 * ⚠️ È l'unica parte che si ripete in tutti e cinque, e si ripete apposta.
 * Ogni template dice cosa CAMBIARE; senza una riga che dica cosa NON cambiare,
 * «cambia l'inquadratura» viene letto come permesso di rifare il resto.
 */
const BLOCCO = [
  'The attached image is the CHARACTER MASTER CEL of this character.',
  'It is the exact and only source of visual truth. This is the SAME character.',
  '',
  'PRESERVE EXACTLY, without reinterpretation:',
  'identity, face construction, anatomy, proportions, silhouette,',
  'hair or hair-equivalent, eyewear, clothing, accessories, colours,',
  'materials, and every distinctive identity detail.',
  '',
  'Do not redesign. Do not reinterpret. Do not add details that are not in the',
  'reference. Do not remove details that are in the reference.',
].join('\n');

/** La coda comune: cosa non deve comparire nel file. */
const CODA = 'No text, no labels, no watermark, no frame borders, no signature.';

/* --- I tre lavori di produzione -------------------------------------------- */

const LAVORO: Partial<Record<AssetType, string[]>> = {
  character_toy: [
    'Use the attached image as the MASTER VISUAL REFERENCE.',
    '',
    'Transform the subject into a high-quality physical collectible toy / designer figure, while preserving the original character design as faithfully as possible.',
    '',
    'PRESERVE EXACTLY',
    '',
    'Keep all defining visual characteristics from the reference image:',
    '',
    '* overall silhouette',
    '* body proportions',
    '* head-to-body ratio',
    '* anatomy',
    '* pose and gesture',
    '* facial expression',
    '* face construction',
    '* eyes and eyewear',
    '* hairstyle, hair volume and hair color',
    '* horns, ears, tails, wings, appendages or unusual anatomy',
    '* clothing design',
    '* clothing volumes',
    '* footwear',
    '* accessories',
    '* palette',
    '* graphic markings',
    '* distinctive identity features',
    '* asymmetries',
    '* unusual or exaggerated proportions',
    '',
    'Do not redesign, reinterpret, simplify, beautify, normalize or replace any element unless necessary to translate it into a physical toy.',
    '',
    'TOY TRANSLATION',
    '',
    'Translate the existing design into a believable premium collectible figure.',
    '',
    'The subject should feel physically manufactured rather than simply rendered in 3D.',
    '',
    'Use:',
    '',
    '* solid sculpted volumes',
    '* clean manufactured surfaces',
    '* premium vinyl / PVC / ABS toy-material logic',
    '* subtle material variation between skin, fabric, plastic, rubber, metal or translucent elements when relevant',
    '* carefully molded hair and clothing',
    '* simplified but faithful physical construction',
    '* precise painted details',
    '* subtle seams only where believable for a manufactured collectible',
    '* rounded physical edges where required by production',
    '* convincing thickness for thin illustrated elements',
    '* stable believable toy construction',
    '',
    'Preserve the original design language even when converting flat illustrated shapes into three-dimensional forms.',
    '',
    'Do not make it look like a realistic human, CGI movie character, action-game render or generic 3D cartoon.',
    '',
    'It must read immediately as the exact same character transformed into a collectible toy.',
    '',
    'RENDER',
    '',
    'Create a polished studio product photograph of the finished collectible figure.',
    '',
    '* full character visible',
    '* centered composition',
    '* clean professional product photography',
    '* soft diffused studio lighting',
    '* subtle grounding shadow',
    '* realistic physical scale',
    '* crisp sculptural detail',
    '* premium collectible presentation',
    '* no packaging',
    '* no props unless they belong to the original character',
    '* no text',
    '* no logo',
    '* no pedestal unless structurally necessary',
    '',
    'BACKGROUND',
    '',
    'Use a completely clean optical white background:',
    '',
    'pure neutral white, bright and seamless, with no cream, beige, warm gray, visible horizon, environment or decorative elements.',
    '',
    'The final image should look like a professionally photographed designer toy on a pure white studio cyclorama.',
    '',
    'Priority order:',
    '',
    '1. preserve the original character',
    '2. preserve silhouette and proportions',
    '3. preserve pose and identity details',
    '4. translate the design into believable toy construction',
    '5. achieve premium studio-product realism',
  ],

  /* §22.2 04 — la griglia delle espressioni. L'ordine è indicizzato per
     posizione dall'app: non è una preferenza, è un contratto. */
  reaction_pack: [
    'PRODUCTION TASK: expression sheet of this character.',
    `One sheet, ${EXPRESSION_SPEC.frames} frames, strict ${EXPRESSION_SPEC.columns} columns x ${EXPRESSION_SPEC.rows} rows grid,`,
    'read left-to-right, top row first. The frame order is FIXED and must not be rearranged:',
    ...EXPRESSION_SPEC.order.map((e, i) => `${String(i + 1).padStart(2, '0')} ${e}`),
    '',
    'Only the facial expression and very small body language change between frames.',
    'Identical bust framing, identical scale, identical eye line in every frame.',
    'Transparent background. Even margins. The sheet must split into',
    `${EXPRESSION_SPEC.frames} equal frames of identical dimensions.`,
  ],

  /* §42 / GB §12 — il doodle è un cambio di MEZZO, non di creatura. */
  bio_doodle: [
    'Use the attached character image as the single and absolute visual source of truth.',
    '',
    'Transform the existing character into an intimate BIO DOODLE / personal sketchbook drawing, while preserving the original character design as faithfully as possible.',
    '',
    'This is not a redesign task.',
    '',
    'Do not reinterpret, simplify, beautify, normalize, restyle, replace or invent any character feature.',
    '',
    'Change only the presentation language from the original image into a loose personal-file doodle.',
    '',
    'CHARACTER LOCK',
    '',
    'Preserve exactly everything that defines the character:',
    '',
    '* overall silhouette',
    '* body proportions',
    '* head-to-body ratio',
    '* anatomy',
    '* number and placement of limbs',
    '* unusual anatomy',
    '* pose and gesture',
    '* facial expression',
    '* face construction',
    '* eye count, eye placement and eye shape',
    '* eyewear',
    '* hairstyle',
    '* hair volume',
    '* hair direction',
    '* hair color',
    '* horns',
    '* ears',
    '* tails',
    '* wings',
    '* rings',
    '* halos',
    '* appendages',
    '* unusual structures',
    '* clothing design',
    '* clothing volumes',
    '* footwear',
    '* accessories',
    '* palette',
    '* color distribution',
    '* graphic markings',
    '* asymmetries',
    '* distinctive identity features',
    '* exaggerated proportions',
    '* unusual silhouette landmarks',
    '',
    'If a feature exists in the reference image, keep it.',
    '',
    'If a feature does not exist in the reference image, do not add it.',
    '',
    'Do not convert non-human anatomy into human anatomy.',
    '',
    'Do not turn the character into a generic humanoid, furry, mascot, superhero, fashion figure or conventional anime character.',
    '',
    'VISUAL PRIORITY',
    '',
    'The final drawing must still be immediately recognizable as the exact same character.',
    '',
    'A viewer should recognize the character before noticing the doodle treatment.',
    '',
    'Preserve the same visual hierarchy as the reference:',
    '',
    '1. dominant silhouette',
    '2. face and expression',
    '3. major anatomy',
    '4. signature identity features',
    '5. clothing and accessory masses',
    '6. palette',
    '7. secondary detail',
    '',
    'Do not allow sketch texture or annotations to overpower the character.',
    '',
    'DOODLE TRANSLATION',
    '',
    'Render the character as an intimate sketchbook drawing made by someone studying or documenting the character personally.',
    '',
    'Use:',
    '',
    '* loose fineliner marks',
    '* ballpoint pen lines',
    '* rough pencil-like construction',
    '* visible underdrawing',
    '* abandoned contours',
    '* doubled lines',
    '* small corrections',
    '* imperfect overlaps',
    '* occasional redraw marks',
    '* sparse handwritten arrows',
    '* tiny underlines',
    '* very small annotation symbols',
    '* small isolated notes',
    '* casual personal-file energy',
    '',
    'The linework should feel spontaneous and human, not vector-clean.',
    '',
    'Keep some visible construction lines around the head, limbs, clothing and major silhouette structures.',
    '',
    'Allow slight inaccuracies in the drawing line, but never in the character design.',
    '',
    'COLOR APPLICATION',
    '',
    'Preserve the original character palette exactly.',
    '',
    'Translate the original colors into 2–5 loose scribbled color applications.',
    '',
    'Use:',
    '',
    '* marker-like fills',
    '* colored pencil blocks',
    '* rough highlighter strokes',
    '* partially unfinished fills',
    '* visible white paper between strokes',
    '',
    'Do not recolor the character.',
    '',
    'Do not introduce a new palette.',
    '',
    'Do not desaturate everything into sepia.',
    '',
    'Do not make the image monochrome unless the source character itself is monochrome.',
    '',
    'Large original color fields must remain visually dominant over line detail.',
    '',
    'ANNOTATIONS',
    '',
    'Add only a few sparse personal sketchbook marks around the silhouette.',
    '',
    'Maximum approximately 2–6 annotations total.',
    '',
    'Possible annotation types:',
    '',
    '* one crooked arrow',
    '* one circled detail',
    '* one tiny underline',
    '* one question mark',
    '* one repeated shape study',
    '* one tiny note',
    '* one correction mark',
    '* one small visual diagram',
    '',
    'Annotations should feel observational and casual.',
    '',
    'Do not add lore.',
    '',
    'Do not invent taxonomy.',
    '',
    'Do not explain the character.',
    '',
    'Do not add large labels.',
    '',
    'Do not create a technical turnaround sheet.',
    '',
    'Do not fill the page with text.',
    '',
    'Annotations must remain secondary to the character.',
    '',
    'NEGATIVE SPACE',
    '',
    'Keep generous white-paper breathing room around the complete character.',
    '',
    'Preserve open negative space inside and around important silhouette structures.',
    '',
    'Do not place annotations over the face.',
    '',
    'Do not fill empty areas inside rings, wings, gaps, limbs or structural openings unless the original design already does.',
    '',
    'PRESENTATION',
    '',
    'Show 100% of the complete character.',
    '',
    'Never crop:',
    '',
    '* hair',
    '* horns',
    '* ears',
    '* wings',
    '* halo',
    '* ring structures',
    '* hands',
    '* feet',
    '* tail',
    '* weapons',
    '* accessories',
    '* appendages',
    '',
    'Keep generous safety margin on every side.',
    '',
    'Maintain the original pose as closely as possible.',
    '',
    'Maintain the original camera angle and body orientation unless a tiny adjustment is necessary to fit the entire character on the page.',
    '',
    'Use a clean white or very slightly warm off-white paper background.',
    '',
    'No environmental background.',
    '',
    'No scene.',
    '',
    'No decorative backdrop.',
    '',
    'No colored background.',
    '',
    'SURFACE LANGUAGE',
    '',
    'The final image should feel approximately:',
    '',
    '* 70% readable character design',
    '* 20% loose construction and sketch energy',
    '* 10% notes, corrections and personal-file detail',
    '',
    'Keep the drawing light, intimate and unfinished.',
    '',
    'Do not turn it into polished concept art.',
    '',
    'Do not make it hyper-detailed.',
    '',
    'Do not make it painterly.',
    '',
    'Do not render realistic materials.',
    '',
    'Do not use cinematic lighting.',
    '',
    'Do not use 3D rendering.',
    '',
    'Do not use glossy toy surfaces.',
    '',
    'Do not use dense crosshatching.',
    '',
    'Do not use heavy black outer contours.',
    '',
    'Do not use comic-panel framing.',
    '',
    'Do not add drop shadows.',
    '',
    'Do not add outer glow.',
    '',
    'Do not add vignette.',
    '',
    'Do not add a drawn frame.',
    '',
    'STYLE TARGET',
    '',
    'The result should feel like:',
    '',
    'the exact same character from the reference image, copied faithfully into a private designer sketchbook using loose pen, visible construction, sparse notes and rough color tests.',
    '',
    'The doodle treatment changes the medium, never the character.',
    '',
    'FINAL CHECK',
    '',
    'Before finishing, verify:',
    '',
    '* same character',
    '* same silhouette',
    '* same proportions',
    '* same anatomy',
    '* same face',
    '* same expression',
    '* same pose',
    '* same hairstyle',
    '* same eyewear',
    '* same clothing',
    '* same accessories',
    '* same unusual anatomy',
    '* same palette',
    '* same asymmetries',
    '* same identity features',
    '',
    'Only the rendering method should change.',
    '',
    'Final result:',
    '',
    'REFERENCE CHARACTER → EXACT CHARACTER PRESERVATION → INTIMATE BIO DOODLE PRESENTATION',
  ],
};

/**
 * Il prompt tecnico di un asset derivato, o `null` se non ne ha uno.
 *
 * 🔒 `null` per il CHARACTER MASTER, e non è un caso mancante: il master è
 * quello che DECIDE, e la sua strada è il Resolver. Un template tecnico per lui
 * sarebbe un personaggio senza nessuno che l'ha pensato.
 */
export function derivedPrompt(assetType: AssetType): string | null {
  const lavoro = LAVORO[assetType];
  if (!lavoro) return null;

  /* Il prompt Toy è stato approvato come testo completo: non aggiungiamo
     prefissi o code automatiche che ne cambierebbero priorità e significato. */
  if (assetType === 'character_toy' || assetType === 'bio_doodle') return lavoro.join('\n');

  return [BLOCCO, '', lavoro.join('\n'), '', `OUTPUT: ${assetTypeDef(assetType).size}.`, CODA].join(
    '\n',
  );
}

/** Gli asset che hanno un template tecnico. Serve ai controlli e a DEV. */
export function derivedCovers(): AssetType[] {
  return (Object.keys(LAVORO) as AssetType[]).filter((t) => LAVORO[t] !== undefined);
}
