import {createServer,type IncomingMessage,type ServerResponse} from 'node:http';
import {resolve} from 'node:path';
import {upsertPersonalMemory} from './correctionAdapter.js';
type M=any;
/* 🔒 PRIVACY — verificato con `lsof` durante il POC (2026-09-17): mem0ai
   manda telemetria a PostHog per default, anche con Ollama locale. Questa
   riga va PRIMA di qualunque `import('mem0ai/oss')` (dentro `getMemory()`,
   più sotto) — non basta impostarla nell'ambiente del processo chiamante,
   se un giorno questo file viene importato da un contesto che non lo fa. */
process.env.MEM0_TELEMETRY ??= 'false';
/* 🔶 «Perché continua a usare OpenAI se abbiamo cambiato con modello locale?»
   Non era mai stato cambiato davvero (MEM0_LLM_PROVIDER/MEM0_EMBEDDER_PROVIDER
   in .env dicevano ancora 'openai') — ma anche cambiandoli, questo controllo
   avrebbe bloccato l'avvio lo stesso: chiedeva SEMPRE una chiave API, anche
   per Ollama, che gira sul Mac e non ne ha bisogno. Ora la chiave è richiesta
   solo per il provider che la usa davvero. */
const ollama=(e:NodeJS.ProcessEnv,k:'MEM0_LLM_PROVIDER'|'MEM0_EMBEDDER_PROVIDER')=>e[k]==='ollama';
export function validateConfig(e=process.env){const required=['VINZMON_MEMORY_SERVICE_SECRET',...(ollama(e,'MEM0_LLM_PROVIDER')?[]:['MEM0_LLM_API_KEY']),...(ollama(e,'MEM0_EMBEDDER_PROVIDER')?[]:['MEM0_EMBEDDER_API_KEY'])];const missing=required.filter(k=>!e[k]);const historyInput=e.MEM0_HISTORY_DB_PATH||'data/mem0-history.sqlite';const vectorInput=e.MEM0_VECTOR_DB_PATH||'data/mem0-vectors.sqlite';if(missing.length)throw Error(`Missing required environment variables: ${missing.join(', ')}`);if(historyInput===':memory:'||vectorInput===':memory:')throw Error('Mem0 persistence cannot use an in-memory database');const history=resolve(historyInput);const vectors=resolve(vectorInput);return {...e,history,vectors} as Record<string,string>}
/* Ollama non vuole (e non capisce) una `apiKey` finta, e la sua base URL è
   quella STESSA variabile già usata altrove nel progetto (`OLLAMA_BASE_URL`,
   vedi `_shared/repoOps.ts`) — non una seconda convenzione di nome. */
const OLLAMA_DEFAULT_BASE_URL=()=>process.env.OLLAMA_BASE_URL||'http://127.0.0.1:11434';
let mp:Promise<M>|undefined; export async function getMemory(){if(!mp)mp=(async()=>{const e=validateConfig();const {Memory}=await import('mem0ai/oss');const llmIsOllama=e.MEM0_LLM_PROVIDER==='ollama';const embedderIsOllama=e.MEM0_EMBEDDER_PROVIDER==='ollama';return new Memory({historyStore:{provider:'sqlite',config:{historyDbPath:e.history}},llm:{provider:e.MEM0_LLM_PROVIDER||'openai',config:{...(llmIsOllama?{}:{apiKey:e.MEM0_LLM_API_KEY}),model:e.MEM0_LLM_MODEL||(llmIsOllama?'qwen2.5:14b':'gpt-5-mini'),baseURL:e.MEM0_LLM_BASE_URL||(llmIsOllama?OLLAMA_DEFAULT_BASE_URL():undefined)}},embedder:{provider:e.MEM0_EMBEDDER_PROVIDER||'openai',config:{...(embedderIsOllama?{}:{apiKey:e.MEM0_EMBEDDER_API_KEY}),model:e.MEM0_EMBEDDER_MODEL||(embedderIsOllama?'nomic-embed-text':'text-embedding-3-small'),embeddingDims:Number(e.MEM0_EMBEDDING_DIMS||(embedderIsOllama?768:1536)),baseURL:e.MEM0_EMBEDDER_BASE_URL||(embedderIsOllama?OLLAMA_DEFAULT_BASE_URL():undefined)}},vectorStore:{provider:'memory',config:{dbPath:e.vectors,dimension:Number(e.MEM0_EMBEDDING_DIMS||(embedderIsOllama?768:1536))}}})})();return mp}
async function readBody(r:IncomingMessage){let s='';for await(const c of r)s+=c;return s?JSON.parse(s):{}}
const out=(r:ServerResponse,n:number,v:unknown)=>{r.writeHead(n,{'content-type':'application/json'});r.end(JSON.stringify(v))}; const authorized=(r:IncomingMessage)=>!!process.env.VINZMON_MEMORY_SERVICE_SECRET&&r.headers.authorization===`Bearer ${process.env.VINZMON_MEMORY_SERVICE_SECRET}`;
/* Solo NOMI di modello, mai chiavi/env — la Control Room li mostra in sola
   lettura (§15 del task: «Mem0's cloud model dependencies read-only»). */
const modelNames=()=>({llmModel:process.env.MEM0_LLM_MODEL||'gpt-5-mini',embedderModel:process.env.MEM0_EMBEDDER_MODEL||'text-embedding-3-small'});
/* 🔷 MEMORY V1 — `agentId` (opzionale, il nome del .mon) su add/search: chi
   non lo manda si comporta esattamente come prima (scope solo `user_id`),
   chi lo manda ottiene l'isolamento per .mon verificato nel POC (Test C). */
export async function app(req:IncomingMessage,res:ServerResponse){if(req.url==='/health'&&req.method==='GET'){try{await getMemory();return out(res,200,{status:'ok',mem0:'ready',vectorStore:'local-sqlite',version:'3.1.7',...modelNames()})}catch(e){return out(res,503,{status:'error',mem0:'not_ready',vectorStore:'local-sqlite',error:e instanceof Error?e.message:'startup_failed',...modelNames()})}}if(!authorized(req))return out(res,401,{error:'unauthorized'});try{const parsed=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);const i=req.method==='GET'?Object.fromEntries(parsed.searchParams):await readBody(req);if(typeof i.userId!=='string'||!i.userId.trim())throw Error('userId is required');const m=await getMemory(),u=i.userId.trim();const agentId=typeof i.agentId==='string'&&i.agentId.trim()?i.agentId.trim():undefined;if(parsed.pathname==='/memory/add'&&req.method==='POST')return out(res,200,await m.add(i.messages??i.text,{userId:u,agentId,metadata:i.metadata,infer:i.infer??true}));if(parsed.pathname==='/memory/search'&&req.method==='POST')return out(res,200,await m.search(String(i.query||''),{filters:{user_id:u,...(agentId?{agent_id:agentId}:{})},topK:i.limit}));if(parsed.pathname==='/memory/upsert'&&req.method==='POST'){if(typeof i.text!=='string'||!i.text.trim())throw Error('text is required');const result=await upsertPersonalMemory(m,{userId:u,agentId,text:i.text},{ollamaModel:process.env.MEM0_LLM_MODEL||'qwen2.5:14b',ollamaBaseUrl:process.env.OLLAMA_BASE_URL||'http://127.0.0.1:11434'});return out(res,200,result)}if(parsed.pathname==='/memory/list'&&req.method==='GET')return out(res,200,await m.getAll({filters:{user_id:u,...(agentId?{agent_id:agentId}:{})},topK:Math.min(Number(i.limit)||500,2000)}));if(parsed.pathname==='/memory/update'&&req.method==='POST')return out(res,200,await m.update(i.memoryId,{text:i.text}));if(parsed.pathname==='/memory/delete'&&req.method==='POST')return out(res,200,await m.delete(i.memoryId));if(parsed.pathname==='/memory/history'&&(req.method==='GET'||req.method==='POST'))return out(res,200,await m.history(i.memoryId));return out(res,404,{error:'not_found'})}catch(e){return out(res,400,{error:e instanceof Error?e.message:'request_failed'})}}
if(process.env.NODE_ENV!=='test'){createServer(app).listen(Number(process.env.PORT||8788),process.env.HOST||'127.0.0.1',()=>console.info('Local Mem0 service ready'))}
