import {createServer,type IncomingMessage,type ServerResponse} from 'node:http';
import {resolve} from 'node:path';
type M=any; const required=['VINZMON_MEMORY_SERVICE_SECRET','MEM0_LLM_API_KEY','MEM0_EMBEDDER_API_KEY'];
export function validateConfig(e=process.env){const missing=required.filter(k=>!e[k]);const historyInput=e.MEM0_HISTORY_DB_PATH||'data/mem0-history.sqlite';const vectorInput=e.MEM0_VECTOR_DB_PATH||'data/mem0-vectors.sqlite';if(missing.length)throw Error(`Missing required environment variables: ${missing.join(', ')}`);if(historyInput===':memory:'||vectorInput===':memory:')throw Error('Mem0 persistence cannot use an in-memory database');const history=resolve(historyInput);const vectors=resolve(vectorInput);return {...e,history,vectors} as Record<string,string>}
let mp:Promise<M>|undefined; export async function getMemory(){if(!mp)mp=(async()=>{const e=validateConfig();const {Memory}=await import('mem0ai/oss');return new Memory({historyStore:{provider:'sqlite',config:{historyDbPath:e.history}},llm:{provider:e.MEM0_LLM_PROVIDER||'openai',config:{apiKey:e.MEM0_LLM_API_KEY,model:e.MEM0_LLM_MODEL||'gpt-5-mini',...(e.MEM0_LLM_BASE_URL?{baseURL:e.MEM0_LLM_BASE_URL}:{})}},embedder:{provider:e.MEM0_EMBEDDER_PROVIDER||'openai',config:{apiKey:e.MEM0_EMBEDDER_API_KEY,model:e.MEM0_EMBEDDER_MODEL||'text-embedding-3-small',embeddingDims:Number(e.MEM0_EMBEDDING_DIMS||1536),...(e.MEM0_EMBEDDER_BASE_URL?{baseURL:e.MEM0_EMBEDDER_BASE_URL}:{})}},vectorStore:{provider:'memory',config:{dbPath:e.vectors,dimension:Number(e.MEM0_EMBEDDING_DIMS||1536)}}})})();return mp}
async function readBody(r:IncomingMessage){let s='';for await(const c of r)s+=c;return s?JSON.parse(s):{}}
const out=(r:ServerResponse,n:number,v:unknown)=>{r.writeHead(n,{'content-type':'application/json'});r.end(JSON.stringify(v))}; const authorized=(r:IncomingMessage)=>!!process.env.VINZMON_MEMORY_SERVICE_SECRET&&r.headers.authorization===`Bearer ${process.env.VINZMON_MEMORY_SERVICE_SECRET}`;
export async function app(req:IncomingMessage,res:ServerResponse){if(req.url==='/health'&&req.method==='GET'){try{await getMemory();return out(res,200,{status:'ok',mem0:'ready',vectorStore:'local-sqlite',version:'3.1.7'})}catch(e){return out(res,503,{status:'error',mem0:'not_ready',vectorStore:'local-sqlite',error:e instanceof Error?e.message:'startup_failed'})}}if(!authorized(req))return out(res,401,{error:'unauthorized'});try{const parsed=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);const i=req.method==='GET'?Object.fromEntries(parsed.searchParams):await readBody(req);if(typeof i.userId!=='string'||!i.userId.trim())throw Error('userId is required');const m=await getMemory(),u=i.userId.trim();if(parsed.pathname==='/memory/add'&&req.method==='POST')return out(res,200,await m.add(i.messages??i.text,{userId:u,metadata:i.metadata,infer:i.infer??true}));if(parsed.pathname==='/memory/search'&&req.method==='POST')return out(res,200,await m.search(String(i.query||''),{filters:{user_id:u},topK:i.limit}));if(parsed.pathname==='/memory/list'&&req.method==='GET')return out(res,200,await m.getAll({filters:{user_id:u}}));if(parsed.pathname==='/memory/update'&&req.method==='POST')return out(res,200,await m.update(i.memoryId,{text:i.text}));if(parsed.pathname==='/memory/delete'&&req.method==='POST')return out(res,200,await m.delete(i.memoryId));if(parsed.pathname==='/memory/history'&&(req.method==='GET'||req.method==='POST'))return out(res,200,await m.history(i.memoryId));return out(res,404,{error:'not_found'})}catch(e){return out(res,400,{error:e instanceof Error?e.message:'request_failed'})}}
if(process.env.NODE_ENV!=='test'){createServer(app).listen(Number(process.env.PORT||8788),process.env.HOST||'127.0.0.1',()=>console.info('Local Mem0 service ready'))}
